### ISSUE TITLE
[Feature Request] Unit Tests

### ISSUE THREAD

**Issue by crutchcorn** [Svehla/ts-generics-RegEx-engine#1]
There is a way to add tests to TypeScript typings [using a Microsoft tool called `dtslint`](https://github.com/microsoft/dtslint)

An example of a typings test might look like this:

https://github.com/oliver-moran/jimp/blob/master/packages/custom/types/test.ts

And would be run like this:

https://github.com/oliver-moran/jimp/blob/master/package.json#L26

I would love to add tests to this beautiful, ridiculous project if for nothing else than to have my commit email in the history haha.

Is this a "contribution" you'd approve?

**Comment by Svehla** [comment]
Hi man!!!

Haha :D I'm soo happy that you like it!

Yes, of course! Feel free to open a pull request! I'll be so happy to share
my happiness + to have tested code for this pretty weird repository! :D

Btw RegEx pattern backtracking is not implemented yet, so some tests may
fail. :D

Best regards,

Jakub Švehla
